[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "raw-data-api"
version = "1.5.27"
requires-python = ">=3.12"
description = "Set of high-performant APIs for transforming and exporting OpenStreetMap (OSM) data in different GIS file formats."
readme = "README.md"
authors = [
    { name = "Hot Tech Team", email = "sysadmin@hotosm.org" }
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
]
keywords = [
    "OSM", "rawdataapi", 
]
dependencies = [
    "alembic==1.13.1",
    "area>=1.1.1",
    "boto3>=1.40.42",
    "celery>=5.5.3",
    "croniter==5.0.1",
    "duckdb>=1.4.0",
    "fastapi>=0.118.0",
    "fastapi-versioning>=0.10.0",
    "geoalchemy2==0.15.2",
    "geojson>=3.2.0",
    "geojson-pydantic>=2.0.0",
    "geojson-stats>=0.2.9",
    "geomet>=1.1.0",
    "hdx-python-api>=6.5.1",
    "humanize>=4.13.0",
    "orjson>=3.11.3",
    "osm-login-python>=2.0.0",
    "psutil>=7.1.0",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.0.0",
    "python-slugify>=8.0.4",
    "pyyaml>=6.0.3",
    "redis>=6.4.0",
    "slowapi>=0.1.9",
    "tqdm>=4.67.1",
    "transliterate>=1.10.2",
    "uvicorn>=0.37.0",
    "zipfly>=6.0.5",
]


[project.urls]
repository = "https://github.com/hotosm/raw-data-api"

[tool.isort]
profile = "black"
import_heading_stdlib = "Standard library imports"
import_heading_thirdparty = "Third party imports"
import_heading_firstparty = "Reader imports"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "pep621"
update_changelog_on_bump = true
version_files = [
    "pyproject.toml:version",]

[project.scripts]
raw-backend = "src.backend.importer:main"
raw-field-update = "src.backend.field_updater:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.build.targets.wheel.force-include]
"src/backend/sql" = "src/backend/sql"
"src/backend/lua" = "src/backend/lua"
"src/backend/sample_data" = "src/backend/sample_data"
"src/backend/countries" = "src/backend/countries"
"src/backend/replication" = "src/backend/replication"

[dependency-groups]
ops = [
    "newrelic>=11.0.0",
    "sentry-sdk>=2.39.0",
]
tests = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
]
backend = [
    "python-dateutil>=2.9.0",
    "requests>=2.32.0",
    "pytz>=2024.1",
    "osmium>=4.0.2",
    "psycopg2>=2.9.10",
]
