#!/usr/bin/env python3
# Copyright (C) 2021 Humanitarian OpenStreetmap Team

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Humanitarian OpenStreetmap Team
# 1100 13th Street NW Suite 800 Washington, D.C. 20005
# <info@hotosm.org>

"""Script to compute and update H3 index for features in a PostGIS table using centroid."""

# Standard library imports
import argparse
import datetime
import logging
import os
import sys
import time
from configparser import ConfigParser
from enum import Enum

# Third party imports
from dateutil.relativedelta import relativedelta
from psycopg2 import *
from psycopg2.extras import *
from tqdm import tqdm

logging.basicConfig(format="%(asctime)s - %(message)s", level=logging.DEBUG)


class BatchFrequency(Enum):
    HOURLY = "h"
    DAILY = "d"
    WEEKLY = "w"
    MONTHLY = "m"
    QUARTERLY = "q"
    YEARLY = "y"

    def __str__(self):
        return self.value


def assign_end_wrt_frequency(start, frequency):
    if frequency == BatchFrequency.HOURLY:
        return start - relativedelta(hours=1)
    if frequency == BatchFrequency.DAILY:
        return start - relativedelta(days=1)
    if frequency == BatchFrequency.WEEKLY:
        return start - relativedelta(weeks=1)
    if frequency == BatchFrequency.MONTHLY:
        return start - relativedelta(months=1)
    if frequency == BatchFrequency.QUARTERLY:
        return start - relativedelta(months=3)
    if frequency == BatchFrequency.YEARLY:
        return start - relativedelta(years=1)


class Database:
    def __init__(self, db_params=None):
        self.db_params = db_params

    def connect(self):
        try:
            self.conn = (
                connect(**self.db_params)
                if self.db_params
                else connect(
                    host=os.environ["PGHOST"],
                    port=os.environ["PGPORT"],
                    user=os.environ["PGUSER"],
                    password=os.environ["PGPASSWORD"],
                    database=os.environ["PGDATABASE"],
                )
            )
            self.cur = self.conn.cursor(cursor_factory=DictCursor)
            return self.conn, self.cur
        except OperationalError as err:
            self.conn = None
            raise err

    def executequery(self, query):
        try:
            if self.conn is not None and query is not None:
                try:
                    self.cur.execute(query)
                    self.conn.commit()
                    try:
                        return self.cur.fetchall()
                    except:
                        return self.cur.statusmessage
                except Exception as err:
                    raise err
            else:
                raise ValueError("Query is null or database is not connected.")
        except Exception as err:
            raise err

    def close_conn(self):
        try:
            if self.conn and self.cur:
                self.cur.close()
                self.conn.close()
        except Exception as err:
            raise err


class H3Updater:
    def __init__(self):
        self.database = Database()
        self.con, self.cur = self.database.connect()

    def getMax_timestamp(self, table):
        query = f"""SELECT min("timestamp") as minimum, max("timestamp") as maximum FROM {table};"""
        record = self.database.executequery(query)
        logging.debug(f"Min: {record[0][0]}, Max: {record[0][1]}")
        return record[0][1], record[0][0]

    def update_h3_column(self, start, end, table, geom_col, h3_col, resolution, init):
        query = f"""WITH updated_rows AS (
            SELECT
                osm_id,
                h3_lat_lng_to_cell(ST_Centroid({geom_col}), {resolution}) AS new_h3
            FROM {table}
            WHERE 
                "timestamp" BETWEEN '{start}' AND '{end}'
                {f"AND {h3_col} IS NULL" if not init else ""}
        )
        UPDATE {table} AS t
        SET {h3_col} = u.new_h3
        FROM updated_rows u
        WHERE t.osm_id = u.osm_id;
        """
        self.database.executequery(query)

    def batch_update_h3(
        self,
        start_batch_date,
        end_batch_date,
        batch_frequency,
        table,
        geom_col,
        h3_col,
        resolution,
        init=False,
    ):
        if start_batch_date is None:
            start_batch_date, _ = self.getMax_timestamp(table)
        if end_batch_date is None:
            _, end_batch_date = self.getMax_timestamp(table)
        if not isinstance(batch_frequency, BatchFrequency):
            raise TypeError("Invalid batch frequency.")

        logging.info(
            f"--- H3 update for {table}.{h3_col} from {start_batch_date} to {end_batch_date} ---"
        )

        looping_date = start_batch_date
        freq_date = start_batch_date
        loop_count = 0

        if batch_frequency in [
            BatchFrequency.WEEKLY,
            BatchFrequency.MONTHLY,
            BatchFrequency.HOURLY,
        ]:
            while freq_date >= end_batch_date:
                loop_count += 1
                freq_date = assign_end_wrt_frequency(freq_date, batch_frequency)
        else:
            loop_count = (looping_date - end_batch_date).days

        with tqdm(total=loop_count, desc=f"Updating {table}:{h3_col}") as pbar:
            while looping_date >= end_batch_date:
                start_date = looping_date
                end_date = assign_end_wrt_frequency(start_date, batch_frequency)
                self.update_h3_column(
                    start=end_date,
                    end=start_date,
                    table=table,
                    geom_col=geom_col,
                    h3_col=h3_col,
                    resolution=resolution,
                    init=init,
                )
                pbar.update(1)
                looping_date = end_date

        self.database.close_conn()
        logging.info(f"--- Finished H3 update for {table}.{h3_col} ---")


if __name__ == "__main__":
    updater = H3Updater()

    parser = argparse.ArgumentParser(
        description="Update H3 column from geometry centroids"
    )
    parser.add_argument(
        "-start",
        "--start",
        type=lambda s: datetime.datetime.strptime(s, "%Y-%m-%d"),
        default=None,
        help="Start date for update. Default: max timestamp in table.",
    )
    parser.add_argument(
        "-end",
        "--end",
        type=lambda s: datetime.datetime.strptime(s, "%Y-%m-%d"),
        default=None,
        help="End date for update. Default: min timestamp in table.",
    )
    parser.add_argument(
        "-f",
        "--frequency",
        type=BatchFrequency,
        choices=list(BatchFrequency),
        default=BatchFrequency.DAILY,
        help="Batch frequency (default: DAILY)",
    )
    parser.add_argument(
        "-table",
        "--table",
        default="ways_poly",
        help="Target table name (default: ways_poly)",
    )
    parser.add_argument(
        "-geom",
        "--geom",
        default="geom",
        help="Geometry column name (default: geom)",
    )
    parser.add_argument(
        "-h3",
        "--h3",
        default="h3",
        help="H3 column name to update (default: h3)",
    )
    parser.add_argument(
        "-res",
        "--resolution",
        type=int,
        default=6,
        help="H3 resolution (default: 8)",
    )
    parser.add_argument(
        "-i",
        "--init",
        action="store_true",
        help="Initial setup of the table (default: False, only for first run)",
    )

    args = parser.parse_args()
    try:
        updater.batch_update_h3(
            start_batch_date=args.start,
            end_batch_date=args.end,
            batch_frequency=args.frequency,
            table=args.table,
            geom_col=args.geom,
            h3_col=args.h3,
            resolution=args.resolution,
            init=args.init,
        )
    except Exception as e:
        logging.error(e)
        sys.exit(1)
